name: Auto Deploy Admin & User Frontend (EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH (base64 safe)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Build & Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "ðŸš€ Deployment started"

            cd /home/ec2-user/Examiify/Examiify-frontend
            git pull origin main

            # ---------- ADMIN FRONTEND ----------
            cd afrontend
            npm install
            NODE_OPTIONS="--max-old-space-size=4096" npm run build

            sudo rm -rf /var/www/examiify-admin/*
            sudo cp -r dist/* /var/www/examiify-admin/
            sudo chown -R nginx:nginx /var/www/examiify-admin
            sudo chcon -R -t httpd_sys_content_t /var/www/examiify-admin

            # ---------- USER FRONTEND ----------
            cd ../userfrontend
            npm install
           NODE_OPTIONS="--max-old-space-size=4096" npm run build

            sudo rm -rf /var/www/examiify/*
            sudo cp -r dist/* /var/www/examiify/
            sudo chown -R nginx:nginx /var/www/examiify
            sudo chcon -R -t httpd_sys_content_t /var/www/examiify

            sudo nginx -t
            sudo systemctl reload nginx

            echo "âœ… Deployment completed"
          EOF
